### ISSUE TITLE
voxpupuli transfer checklist

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-drbd#24]
- [x] enable issues
- [x] allow access to @voxpupuli/collaborators 
- [x] normalise repository name
- [ ] fix links in README
- [ ] fix links in metadata.json
- [x] enable in travis
- [x] add to modulesync_config/modules
- [x] add to plumbing/travis_secrets
- [ ] add .sync.yml
- [ ] modulesync
- [ ] release under new namespace!
- [x] make master branch protected
- [x] Require status checks to pass before merging
- [x] Require branches to be up to date before merging (Include administrators)
- [x] remove all webhooks except for travis
- [x] remove all old teams that had access before

**Comment by bastelfreak** [comment]
- [] make master branch protected
- [] Require status checks to pass before merging
- [] Require branches to be up to date before merging (Include administrators)

**Comment by bastelfreak** [comment]
[ ] remove all webhooks except for travis
[ ] remove all old teams that had access before

**Comment by igalic** [comment]
i've added your contributions to the checklist into the issue, so we can use the issue as a template later on

**Comment by zilchms** [comment]
Fully migrated and checklist completed
